import type { Metadata } from "next";
import "./globals.css";
import { AnimationProvider } from "../context/AnimationContext";
import Header from "../components/layout/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AnimationProvider>
        <body className={`antialiased`}>
          <Header />
          {children}
        </body>
      </AnimationProvider>
    </html>
  );
}
